#开发配置
server:
  port: 9100
spring:
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 102400KB
      # 一次请求文件大小
      max-request-size: 102400KB
  datasource:
    url: jdbc:mysql://mysql:3306/tzzd?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root123
  redis:
    host: radis
    database: 0
    port: 6379
    password: ''
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0

logging:
  level:
    com.ttit.tzzd.manager.dao: debug
    com.ttit.tzzd.sys.dao: debug

business:
  server:
    #对外暴露附件服务的根路径
    atta-url: 172.18.0.58:9100
  dict:
    #使用内建版数据字典
    save-type: "app"
  log:
    #日志级别all，代表用户任何操作都会被记录到系统日志（数据库）中
    level: "all"
  time-limit:
    #设备连接时限，单位秒
    #上次收到信号，在online时间内，视为在线
    online: 10
    #上次收到信号，超过online时间，小于breaked时间，视为中断；大于breaked时间，视为离线
    breaked: 40
  file-upload-path: /opt/tzzd/data/softs