#开发配置
server:
  port: 9100
spring:
  datasource:
    url: jdbc:mysql://172.18.0.58:3306/tzzd
    username: root
    password: root123
  redis:
    host: 172.18.0.58
    database: 0
    port: 6379
    password: ''
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0