version: '3'
services:
  mysql:
    image: 'mysql/mysql-server:5.7'
#    container_name: tzzd-db
    networks:
      tzzd-network:
#    ports:
#      - '3306:3306'
    #设置utf8字符集
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d/
    environment:
      - "MYSQL_ROOT_PASSWORD=root123"
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_DATABASE=tzzd"
    restart: always
  redis:
    image: 'redis:latest'
    networks:
      tzzd-network:
#    ports:
#      - '6379:6379'
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
    restart: always
  zookeeper:
    image: zookeeper:3.4
#    ports:
#      - 2181:2181
    networks:
      tzzd-network:
    restart: always
  dubbo-admin:
    build:
      context: ./dubbo-admin/
      dockerfile: Dockerfile
    links:
      - zookeeper:zookeeper
    depends_on:
      - zookeeper
    ports:
      - 7001:7001
    networks:
      tzzd-network:
    restart: always
  web-server:
    build:
      context: ./web-server/
      dockerfile: Dockerfile
    links:
      - mysql:mysql
      - redis:redis
    depends_on:
      - mysql
      - redis
    ports:
      - 9100:9100
    volumes:
      - ./web-server/data:/opt/tzzd/data
    networks:
      tzzd-network:
    restart: always
networks:
  tzzd-network:
    ipam:
      config:
        - subnet: 172.19.0.0/16
