version: '3'
services:
  mysql:
    image: 'mysql/mysql-server:5.7'
#    container_name: tzzd-db
    networks:
      tzzd-network:
        ipv4_address: 172.19.0.2
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d/
    environment:
      - "MYSQL_ROOT_PASSWORD=root123"
      - "MYSQL_DATABASE=tzzd"
      - "MYSQL_ROOT_HOST=%"
    restart: always
  redis:
    image: 'redis:latest'
    networks:
      tzzd-network:
        ipv4_address: 172.19.0.3
    ports:
      - '6379:6379'
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
    restart: always
  zookeeper:
    image: zookeeper:3.4
    ports:
      - 2181:2181
    networks:
      tzzd-network:
        ipv4_address: 172.19.0.4
    restart: always
  dubbo-admin:
    build:
      context: ./dubbo-admin/
      dockerfile: Dockerfile
    links:
      - zookeeper:zookeeper
    depends_on:
      - zookeeper
    ports:
      - 7001:7001
    networks:
      tzzd-network:
        ipv4_address: 172.19.0.5
    restart: always

networks:
  tzzd-network:
    ipam:
      config:
        - subnet: 172.19.0.0/16
